[[docs]]
  name = "এসএসসি"
  weight = 10
  identifier = "ssc"
  url = "/class/ssc/"

[[docs]]
  name = "এইচএসসি"
  weight = 20
  identifier = "hsc"
  url = "/class/hsc/"
  
[[docs]]
  name = "এডমিশন"
  weight = 30
  identifier = "admission"
  url = "/class/admission/"

[[main]]
  name = "ডোনেট"
  url = "/donate/"
  weight = 10

[[main]]
  name = "ব্লগ"
  url = "/blog/"
  weight = 20

 [[main]]
  name = "যোগাযোগ"
  url = "/contact/"
  weight = 20 

[[social]]
  name = "টুইটার"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/abusayed0206"
  weight = 10


[[footer]]
  name = "গোপনীয়তা নীতি"
  url = "/privacy-policy/"
  weight = 10
[[footer]]
  name = "টুইটার"
  url = "https://twitter.com/abusayed0206"
  weight = 12
  [[footer]]
  name = "টেলিগ্রাম গ্রুপ"
  url = "https://t.me/opensourcebangladeshgroup"
  weight = 12